linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - contextcheck
    - copyloopvar
    - errcheck
    - exhaustive
    - forcetypeassert
    - goimports
    - gosimple
    - govet
    - ineffassign
    - predeclared
    - staticcheck
    - usetesting
    - typecheck
    - unused
    - whitespace
